name: cli terraform
on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  terraform:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.0

    - name: terraform init
      run: |
        cd terraform
        terraform init

    - name: terraform plan
      run: |
        cd terraform
        terraform plan 

    - name: terraform apply
      run: |
        cd terraform
        terraform apply -auto-approve